name: Android Emulator

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Set up Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 5X API 30
          tag: google_apis_playstore
      - name: Run emulator tests
        run: ./gradlew connectedCheck
